set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 10

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g status-style 'bg=#333333 fg=#5eacd3'

bind r source-file ~/.tmux.conf
bind e move-window -r
set -g base-index 1

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'


# Cmd+number (Mac) / Ctrl+number (Linux) window switching via alacritty escape sequences
set -s user-keys[0] "\e[101~"
set -s user-keys[1] "\e[102~"
set -s user-keys[2] "\e[103~"
set -s user-keys[3] "\e[104~"
set -s user-keys[4] "\e[105~"
set -s user-keys[5] "\e[106~"
set -s user-keys[6] "\e[107~"
set -s user-keys[7] "\e[108~"
set -s user-keys[8] "\e[109~"
set -s user-keys[9] "\e[110~"
bind-key -n User0 select-window -t 1
bind-key -n User1 select-window -t 2
bind-key -n User2 select-window -t 3
bind-key -n User3 select-window -t 4
bind-key -n User4 select-window -t 5
bind-key -n User5 select-window -t 6
bind-key -n User6 select-window -t 7
bind-key -n User7 select-window -t 8
bind-key -n User8 select-window -t 9
bind-key -n User9 select-window -t 10

# tmux sessionizer from ThePrimagen
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

bind -r h neww "nvim ~/work/reflect/2026-reflections.md"
bind -r j neww -c "#{pane_current_path}" "[[ -e TODO.md ]] && nvim TODO.md || nvim ~/work/manage/todo.md"
bind -r k neww "nvim ~/work/rocks/2026-q1"
bind -r i neww  "nvim ~/dotfiles/linux/linkr/.config/linkr/config"
